### ISSUE TITLE
PWM

### ISSUE THREAD

**Issue by FoxyCTG21** [Obijuan/digital-electronics-with-open-FPGAs-tutorial#12]
Me interesa saber mas y como efectuar el uso de entradas y salidas PWM, se espera en segunda temporada un o unos tutoriales de PWM?

**Comment by Obijuan** [comment]
En este cuaderno técnico hay información sobre cómo hacer Unidades de PWM:

https://github.com/Obijuan/Cuadernos-tecnicos-FPGAs-libres/wiki/CT.1:-Unidad-de-PWM-de-frecuencia-aproximada
