### ISSUE TITLE
Tabla verdad puerta And

### ISSUE THREAD

**Issue by tecnologiapedromercedes** [Obijuan/digital-electronics-with-open-FPGAs-tutorial#5]
Creo que hay un error en la tabla de verdad de la puerta And. Has puesto tres combinaciones iguales de entrada 00,00,00,01 en lugar de 00,01,10,11.
Saludos y gracias por el trabajazo.

**Comment by Obijuan** [comment]
¡Gracias! Corregido :-)

(refresca la caché del navegador para ver la nueva tabla)
