### ISSUE TITLE
T18, Tabla valores parametros ServoBit

### ISSUE THREAD

**Issue by rodalillo** [Obijuan/digital-electronics-with-open-FPGAs-tutorial#6]
Buenos días,

Revisando el tutorial, he dudado en una tabla, ya que lo valores parece que estén cambiados.
[Vídeo-18:-Bloques-con-parámetros > Tabla de valores para los parámetros (PX)](https://github.com/Obijuan/digital-electronics-with-open-FPGAs-tutorial/wiki/V%C3%ADdeo-18:-Bloques-con-par%C3%A1metros#tabla-de-valores-de-los-par%C3%A1metros-px)

Si el Futaba se coge como referencia, en los otros dos servos tiene que haber una correspondencia.
¿Los valores de P0 deberían ser menores que P1?

Servo	Pmax(μs)	Pmin(μs)	P1(μs)	P0(μs)
Futaba 3003	2410	380	1670	820
Emax-ES808A	2550	580	**1000	2000**
TowerPro SG-90	2350	500	**1000	2000**

Saludos,

**Comment by Obijuan** [comment]
Es una errata. ¡Gracias! Ya lo he corregido. Los valores están al revés :-)
