### ISSUE TITLE
Archivos con caracteres inválidos en Windows

### ISSUE THREAD

**Issue by ximocat** [Obijuan/digital-electronics-with-open-FPGAs-tutorial#7]
@Obijuan alguien ha subido 3 ficheros con caracteres inválidos en Windows, por lo que no puedo hacer un merge de tu repositorio en mi clon. ¿Podrías eliminar esos tres ficheros?

Estos son los ficheros:
```
Tutorial-6/maxezek/Screenshot at 2018-05-10 19:53:14.png
Tutorial-8/Screenshot at 2018-05-20 13:11:43.png
Tutorial-8/maxezek/Screenshot at 2018-05-20 13:11:43.png
```
El carácter inválido es `:`.

**Comment by Obijuan** [comment]
Solucionado! Prueba ahora..

Cualquier problema me lo comentas en esta issue. La cierro cuando se solucione

**Comment by ximocat** [comment]
Ok, ya funciona.

Lo que no entiendo es por qué narices puse aquí la issue en vez de en el repositorio de entrega :)

Muchas Gracias

**Comment by Obijuan** [comment]
¡Sin problemas! :-)
