### ISSUE TITLE
Error ortográfico

### ISSUE THREAD

**Issue by albertovn** [Obijuan/digital-electronics-with-open-FPGAs-tutorial#9]
Hola. En el apartado 'Video 3...', sección 'FPGAs libres', segundo párrafo (después del dibujo) hay un texto que pone 'y sólo se puede hacer con ellas lo que el fabricante **a** decidido que se puede hacer'. La 'a' debería llevar hache. Perdón por la corrección, lo he visto y he tenido que abrir ticket...
En cualquier caso, excelente tutorial, llevo mucho tiempo desarrollando por ocio con Arduino y gracias a este proyecto de FPGAwars ya sé qué pedir para reyes 😃.

**Comment by Obijuan** [comment]
¡Un error muy gordo! Gracias por avisar. Ya está corregido :-)
